### ISSUE TITLE
meryl version

### ISSUE THREAD

**Issue by lurebgi** [skoren/triobinningScripts#3]
Hi,

I was trying to run the scripts steps by steps, however, I am not sure which version of meryl to use. 

The one from canu-1.7.1 looks like what you used, but does not have the 'difference' in -M options.
The one from canu-1.8 looks quite different, with different usage.

I also tried the original package from http://kmer.sourceforge.net/wiki/index.php?Main_Page, but it also has no '-M difference' option.

Thanks,

Luohao

**Comment by skoren** [comment]
The appropriate version is linked as a submodule in this repo under meryl. It should be close to the 1.7 release version, the documentation will not list -M difference but will still run.

**Comment by lurebgi** [comment]
Thanks, '-M difference' works in 1.7 release.
