### ISSUE TITLE
meryl

### ISSUE THREAD

**Issue by duhuipeng** [skoren/triobinningScripts#6]
![image](https://user-images.githubusercontent.com/58722433/105458376-63f04180-5cc3-11eb-8f20-e548e313496e.png)

Dear author
I want to know how to find out which one is worth ,In other words, how these two values are seen in the graph

![image](https://user-images.githubusercontent.com/58722433/105458586-d5c88b00-5cc3-11eb-9df0-4623ccf4b369.png)
this is graph,But I don't know how to choose

**Comment by duhuipeng** [comment]
I found that the software had been updated and I used your code in hicanu to run this step,as follow:
/opt/software/canu1.8/Linux-amd64/bin/meryl count k=21 reads.fasta output reads.k21
But I'd like to know if the files I get through this step through the updated code will have an impact on the kmer of the features I' ll look for later on
What I'd like to ask is if this parameter change can be followed by meryl, use your meryl code,as follow:
![image](https://user-images.githubusercontent.com/58722433/104985433-e5d63580-5a4b-11eb-83d3-31f4b5e8b065.png)

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/105465157-8edf9300-5ccd-11eb-94af-4074215643c5.png)
Is it through this to determine it threshold( means :25,150 in the code)

**Comment by skoren** [comment]
Chose the first value at the first dip (around 20 it looks like) and the second past the main peaks (around 200 in the graph). If you use the trio binning module built into Canu, it will automatically select these thresholds for you.

**Comment by duhuipeng** [comment]
thank you, I got it

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/105933528-8ac6c300-6089-11eb-8734-49ed67d42920.png)
Dear author
The new version I used meryl, I wanted to know what parameters I used to replace - Dh, histogram made
